#include "src/game/envfx_snow.h"

const GeoLayout ccm_area_1_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_NODE_WITH_DL(1, -497, 310, -1717, ccm_dl_Castle_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(1, -459, 1564, -1454, ccm_dl_Castle_001_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(1, -9136, 2127, 6238, ccm_dl_Ground_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(1, -13841, 2127, -4276, ccm_dl_Ground_002_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(1, -9065, 2127, 2073, ccm_dl_Ground_003_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(1, -12651, 2127, -834, ccm_dl_Ground_004_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(1, -7371, 2127, -4565, ccm_dl_Ground_005_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(1, 0, 310, 0, ccm_dl_Lava_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout ccm_area_1[] = {
	GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
	GEO_OPEN_NODE(),
		GEO_ZBUFFER(0),
		GEO_OPEN_NODE(),
			GEO_NODE_ORTHO(100.0000),
			GEO_OPEN_NODE(),
				GEO_BACKGROUND(BACKGROUND_FLAMING_SKY, geo_skybox_main),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_ZBUFFER(1),
		GEO_OPEN_NODE(),
			GEO_CAMERA_FRUSTUM_WITH_FUNC(45.0000, 100, 30000, geo_camera_fov),
			GEO_OPEN_NODE(),
				GEO_CAMERA(CAMERA_MODE_8_DIRECTIONS, 0, 0, 0, 0, -100, 0, geo_camera_main),
				GEO_OPEN_NODE(),
					GEO_BRANCH(1, ccm_area_1_geo),
					GEO_RENDER_OBJ(),
					GEO_ASM(ENVFX_MODE_NONE, geo_envfx_main),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(1, ccm_dl_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
