extern void scroll_castle_courtyard_dl_L1Box_mesh_layer_1_vtx_5();
extern void scroll_castle_courtyard_dl_L3Box_mesh_layer_1_vtx_0();
extern void scroll_castle_courtyard_dl_L3Box_mesh_layer_1_vtx_3();
extern void scroll_castle_courtyard();
