extern const GeoLayout block_q[];
extern const GeoLayout block_hit[];
extern const GeoLayout block_geo[];
extern Lights1 block_bblock_lights;
extern Lights1 block_qblock2_lights;
extern Lights1 block_qblock_lights;
extern Lights1 block_hitblock_lights;
extern u8 block_bbrick_ci4[];
extern u8 block_bbrick_ci4_pal_rgba16[];
extern u8 block_qblock2_ci4[];
extern u8 block_qblock2_ci4_pal_rgba16[];
extern u8 block_qblock_ci4[];
extern u8 block_qblock_ci4_pal_rgba16[];
extern u8 block_hitblock_ci4[];
extern u8 block_hitblock_ci4_pal_rgba16[];
extern Vtx block_root_mesh_layer_1_vtx_0[24];
extern Gfx block_root_mesh_layer_1_tri_0[];
extern Vtx block_option_root2_mesh_layer_1_vtx_0[16];
extern Gfx block_option_root2_mesh_layer_1_tri_0[];
extern Vtx block_option_root2_mesh_layer_1_vtx_1[8];
extern Gfx block_option_root2_mesh_layer_1_tri_1[];
extern Vtx block_option_root3_mesh_layer_1_vtx_0[24];
extern Gfx block_option_root3_mesh_layer_1_tri_0[];
extern Gfx mat_block_bblock[];
extern Gfx mat_revert_block_bblock[];
extern Gfx mat_block_qblock2[];
extern Gfx mat_revert_block_qblock2[];
extern Gfx mat_block_qblock[];
extern Gfx mat_revert_block_qblock[];
extern Gfx mat_block_hitblock[];
extern Gfx mat_revert_block_hitblock[];
extern Gfx block_root_mesh_layer_1[];
extern Gfx block_option_root2_mesh_layer_1[];
extern Gfx block_option_root3_mesh_layer_1[];
extern Gfx block_material_revert_render_settings[];
