extern const GeoLayout ccm_area_1_geo[];
extern const GeoLayout ccm_area_1[];
extern const Collision ccm_area_1_collision[];
extern const MacroObject ccm_area_1_macro_objs[];
extern const Trajectory ccm_area_1_spline_KoopaPath[];
extern Lights1 ccm_dl_Castle_lights;
extern Lights1 ccm_dl_Grounds_lights;
extern Lights1 ccm_dl_Lava2_lights;
extern u8 ccm_dl_whitebricks_i8[];
extern u8 ccm_dl_CrossCarpetBig_ia8[];
extern u8 ccm_dl_ci4_matt_lava_ci4[];
extern u8 ccm_dl_ci4_matt_lava_ci4_pal_rgba16[];
extern u8 ccm_dl_dirtwall_ci8[];
extern u8 ccm_dl_dirtwall_ci8_pal_rgba16[];
extern Vtx ccm_dl_Castle_mesh_layer_1_vtx_cull[8];
extern Vtx ccm_dl_Castle_mesh_layer_1_vtx_0[225];
extern Gfx ccm_dl_Castle_mesh_layer_1_tri_0[];
extern Vtx ccm_dl_Castle_mesh_layer_1_vtx_1[6];
extern Gfx ccm_dl_Castle_mesh_layer_1_tri_1[];
extern Vtx ccm_dl_Castle_mesh_layer_1_vtx_2[4];
extern Gfx ccm_dl_Castle_mesh_layer_1_tri_2[];
extern Vtx ccm_dl_Castle_001_mesh_layer_1_vtx_cull[8];
extern Vtx ccm_dl_Castle_001_mesh_layer_1_vtx_0[43];
extern Gfx ccm_dl_Castle_001_mesh_layer_1_tri_0[];
extern Vtx ccm_dl_Ground_mesh_layer_1_vtx_cull[8];
extern Vtx ccm_dl_Ground_mesh_layer_1_vtx_0[46];
extern Gfx ccm_dl_Ground_mesh_layer_1_tri_0[];
extern Vtx ccm_dl_Ground_001_mesh_layer_1_vtx_cull[8];
extern Vtx ccm_dl_Ground_001_mesh_layer_1_vtx_0[46];
extern Gfx ccm_dl_Ground_001_mesh_layer_1_tri_0[];
extern Vtx ccm_dl_Lava_mesh_layer_1_vtx_cull[8];
extern Vtx ccm_dl_Lava_mesh_layer_1_vtx_0[46];
extern Gfx ccm_dl_Lava_mesh_layer_1_tri_0[];
extern Gfx mat_ccm_dl_Castle[];
extern Gfx mat_revert_ccm_dl_Castle[];
extern Gfx mat_ccm_dl_CastleCarpet_layer1[];
extern Gfx mat_revert_ccm_dl_CastleCarpet_layer1[];
extern Gfx mat_ccm_dl_Lava3[];
extern Gfx mat_revert_ccm_dl_Lava3[];
extern Gfx mat_ccm_dl_Grounds[];
extern Gfx mat_revert_ccm_dl_Grounds[];
extern Gfx mat_ccm_dl_Lava2[];
extern Gfx mat_revert_ccm_dl_Lava2[];
extern Gfx ccm_dl_Castle_mesh_layer_1[];
extern Gfx ccm_dl_Castle_001_mesh_layer_1[];
extern Gfx ccm_dl_Ground_mesh_layer_1[];
extern Gfx ccm_dl_Ground_001_mesh_layer_1[];
extern Gfx ccm_dl_Lava_mesh_layer_1[];
extern Gfx ccm_dl_material_revert_render_settings[];
