extern const GeoLayout castle_grounds_area_1_geo[];
extern const GeoLayout castle_grounds_area_1[];
extern const Collision castle_grounds_area_1_collision[];
extern const MacroObject castle_grounds_area_1_macro_objs[];
extern Lights1 castle_grounds_dl_WoodFloor_lights;
extern Lights1 castle_grounds_dl_Wall_layer1_lights;
extern u8 castle_grounds_dl_ci8_custom_planks5_ci8[];
extern u8 castle_grounds_dl_ci8_custom_planks5_ci8_pal_rgba16[];
extern u8 castle_grounds_dl_wall_rgba16[];
extern u8 castle_grounds_dl_wall_multitex_rgba16[];
extern Vtx castle_grounds_dl_workshop_mesh_layer_1_vtx_0[9];
extern Gfx castle_grounds_dl_workshop_mesh_layer_1_tri_0[];
extern Vtx castle_grounds_dl_workshop_mesh_layer_1_vtx_1[40];
extern Gfx castle_grounds_dl_workshop_mesh_layer_1_tri_1[];
extern Gfx mat_castle_grounds_dl_WoodFloor[];
extern Gfx mat_revert_castle_grounds_dl_WoodFloor[];
extern Gfx mat_castle_grounds_dl_Wall_layer1[];
extern Gfx mat_revert_castle_grounds_dl_Wall_layer1[];
extern Gfx castle_grounds_dl_workshop_mesh_layer_1[];
extern Gfx castle_grounds_dl_material_revert_render_settings[];
