extern const GeoLayout gate_switch_opt1[];
extern const GeoLayout gate_geo[];
extern u8 gate_MetalGround_i8[];
extern u8 gate_metal_i8[];
extern Vtx gate_dl_mesh_layer_1_vtx_0[16];
extern Gfx gate_dl_mesh_layer_1_tri_0[];
extern Vtx gate_dl_mesh_layer_1_vtx_1[4];
extern Gfx gate_dl_mesh_layer_1_tri_1[];
extern Gfx mat_gate_Gate_001[];
extern Gfx mat_gate_Metal[];
extern Gfx gate_dl_mesh_layer_1[];
extern Gfx gate_material_revert_render_settings[];
