extern const GeoLayout bob_area_1_geo[];
extern const GeoLayout bob_area_1[];
extern const Collision bob_area_1_collision[];
extern const MacroObject bob_area_1_macro_objs[];
extern Lights1 bob_dl_BrickBlock_lights;
extern Lights1 bob_dl_Grass_lights;
extern u8 bob_dl_bricks_ci4[];
extern u8 bob_dl_bricks_ci4_pal_rgba16[];
extern u8 bob_dl_i8_grass_i8[];
extern u8 bob_dl_dirtwall_grass_ci8[];
extern u8 bob_dl_dirtwall_grass_ci8_pal_rgba16[];
extern Vtx bob_dl_BrickBlock_mesh_layer_1_vtx_0[24];
extern Gfx bob_dl_BrickBlock_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Grass_mesh_layer_1_vtx_0[64];
extern Gfx bob_dl_Grass_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Grass_mesh_layer_1_vtx_1[66];
extern Gfx bob_dl_Grass_mesh_layer_1_tri_1[];
extern Vtx bob_dl_GrassPlat_mesh_layer_1_vtx_0[4];
extern Gfx bob_dl_GrassPlat_mesh_layer_1_tri_0[];
extern Vtx bob_dl_GrassPlat_mesh_layer_1_vtx_1[16];
extern Gfx bob_dl_GrassPlat_mesh_layer_1_tri_1[];
extern Gfx mat_bob_dl_BrickBlock[];
extern Gfx mat_revert_bob_dl_BrickBlock[];
extern Gfx mat_bob_dl_Grass[];
extern Gfx mat_revert_bob_dl_Grass[];
extern Gfx mat_bob_dl_DirtEdge[];
extern Gfx mat_revert_bob_dl_DirtEdge[];
extern Gfx bob_dl_BrickBlock_mesh_layer_1[];
extern Gfx bob_dl_Grass_mesh_layer_1[];
extern Gfx bob_dl_GrassPlat_mesh_layer_1[];
extern Gfx bob_dl_material_revert_render_settings[];
