extern const GeoLayout portal_blocker_geo[];
extern u8 portal_blocker_mirror2_ci8[];
extern u8 portal_blocker_mirror2_ci8_pal_rgba16[];
extern u8 portal_blocker_xx_1_lighter2_ci8[];
extern u8 portal_blocker_xx_1_lighter2_ci8_pal_rgba16[];
extern Vtx portal_blocker_Portal1_001_mesh_layer_5_vtx_cull[8];
extern Vtx portal_blocker_Portal1_001_mesh_layer_5_vtx_0[4];
extern Gfx portal_blocker_Portal1_001_mesh_layer_5_tri_0[];
extern Vtx portal_blocker_Portal1_001_mesh_layer_1_vtx_cull[8];
extern Vtx portal_blocker_Portal1_001_mesh_layer_1_vtx_0[24];
extern Gfx portal_blocker_Portal1_001_mesh_layer_1_tri_0[];
extern Gfx mat_portal_blocker_Portal_001[];
extern Gfx mat_revert_portal_blocker_Portal_001[];
extern Gfx mat_portal_blocker_Wood[];
extern Gfx mat_revert_portal_blocker_Wood[];
extern Gfx portal_blocker_Portal1_001_mesh_layer_5[];
extern Gfx portal_blocker_Portal1_001_mesh_layer_1[];
extern Gfx portal_blocker_material_revert_render_settings[];
