extern const GeoLayout bounce_hill_switch_opt1[];
extern const GeoLayout bounce_hill_switch_opt2[];
extern const GeoLayout bounce_hill_geo[];
extern Lights1 bounce_hill_hills_001_lights;
extern Lights1 bounce_hill_hills2_lights;
extern Lights1 bounce_hill_hills3_lights;
extern u8 bounce_hill_star_eye_rgba16_ia8[];
extern u8 bounce_hill_hillstripes1_ci4[];
extern u8 bounce_hill_hillstripes1_ci4_pal_rgba16[];
extern u8 bounce_hill_hillstripes2_ci4[];
extern u8 bounce_hill_hillstripes2_ci4_pal_rgba16[];
extern u8 bounce_hill_hillstripes3_ci4[];
extern u8 bounce_hill_hillstripes3_ci4_pal_rgba16[];
extern Vtx bounce_hill_dl2_mesh_layer_6_vtx_0[8];
extern Gfx bounce_hill_dl2_mesh_layer_6_tri_0[];
extern Vtx bounce_hill_dl_mesh_layer_1_vtx_0[59];
extern Gfx bounce_hill_dl_mesh_layer_1_tri_0[];
extern Gfx mat_bounce_hill_eyes[];
extern Gfx mat_bounce_hill_hills_001[];
extern Gfx mat_revert_bounce_hill_hills_001[];
extern Gfx mat_bounce_hill_hills2[];
extern Gfx mat_revert_bounce_hill_hills2[];
extern Gfx mat_bounce_hill_hills3[];
extern Gfx mat_revert_bounce_hill_hills3[];
extern Gfx bounce_hill_dl2_mesh_layer_6[];
extern Gfx bounce_hill_dl_mesh_layer_1[];
extern Gfx bounce_hill_dl_mesh_layer_1_mat_override_hills2_0[];
extern Gfx bounce_hill_dl_mesh_layer_1_mat_override_hills3_1[];
extern Gfx bounce_hill_material_revert_render_settings[];
