extern const GeoLayout beat_block_fillred[];
extern const GeoLayout beat_block_fillblue[];
extern const GeoLayout beat_block_geo[];
extern Lights1 beat_block_white_lights;
extern Lights1 beat_block_red_lights;
extern Lights1 beat_block_blue_lights;
extern u8 beat_block_chikachikablock_ai_emm01_ci8[];
extern u8 beat_block_chikachikablock_ai_emm01_ci8_pal_rgba16[];
extern u8 beat_block_chikachikablock_ai_emm02_ci8[];
extern u8 beat_block_chikachikablock_ai_emm02_ci8_pal_rgba16[];
extern Vtx beat_block_root_mesh_layer_1_vtx_0[188];
extern Gfx beat_block_root_mesh_layer_1_tri_0[];
extern Vtx beat_block_option_rroot_mesh_layer_1_vtx_0[24];
extern Gfx beat_block_option_rroot_mesh_layer_1_tri_0[];
extern Vtx beat_block_option_broot_mesh_layer_1_vtx_0[24];
extern Gfx beat_block_option_broot_mesh_layer_1_tri_0[];
extern Gfx mat_beat_block_white[];
extern Gfx mat_beat_block_red[];
extern Gfx mat_revert_beat_block_red[];
extern Gfx mat_beat_block_blue[];
extern Gfx mat_revert_beat_block_blue[];
extern Gfx beat_block_root_mesh_layer_1[];
extern Gfx beat_block_option_rroot_mesh_layer_1[];
extern Gfx beat_block_option_broot_mesh_layer_1[];
extern Gfx beat_block_material_revert_render_settings[];
