extern const GeoLayout rank_display_switch_opt1[];
extern const GeoLayout rank_display_switch_opt2[];
extern const GeoLayout rank_display_switch_opt3[];
extern const GeoLayout rank_display_switch_opt4[];
extern const GeoLayout rank_display_switch_opt5[];
extern const GeoLayout rank_display_geo[];
extern Lights1 rank_display_bestrank_lights;
extern u8 rank_display_bestrank_ia8[];
extern u8 rank_display_s_ci8[];
extern u8 rank_display_s_ci8_pal_rgba16[];
extern u8 rank_display_a_ci8[];
extern u8 rank_display_a_ci8_pal_rgba16[];
extern u8 rank_display_b_ci8[];
extern u8 rank_display_b_ci8_pal_rgba16[];
extern u8 rank_display_c_ci8[];
extern u8 rank_display_c_ci8_pal_rgba16[];
extern u8 rank_display_d_ci8[];
extern u8 rank_display_d_ci8_pal_rgba16[];
extern u8 rank_display_f_ci8[];
extern u8 rank_display_f_ci8_pal_rgba16[];
extern Vtx rank_display_root_mesh_layer_4_vtx_0[4];
extern Gfx rank_display_root_mesh_layer_4_tri_0[];
extern Vtx rank_display_letter_mesh_layer_4_vtx_0[4];
extern Gfx rank_display_letter_mesh_layer_4_tri_0[];
extern Gfx mat_rank_display_bestrank[];
extern Gfx mat_revert_rank_display_bestrank[];
extern Gfx mat_rank_display_s[];
extern Gfx mat_revert_rank_display_s[];
extern Gfx mat_rank_display_a[];
extern Gfx mat_revert_rank_display_a[];
extern Gfx mat_rank_display_b[];
extern Gfx mat_revert_rank_display_b[];
extern Gfx mat_rank_display_c[];
extern Gfx mat_revert_rank_display_c[];
extern Gfx mat_rank_display_d[];
extern Gfx mat_revert_rank_display_d[];
extern Gfx mat_rank_display_f[];
extern Gfx mat_revert_rank_display_f[];
extern Gfx rank_display_root_mesh_layer_4[];
extern Gfx rank_display_letter_mesh_layer_4[];
extern Gfx rank_display_letter_mesh_layer_4_mat_override_a_0[];
extern Gfx rank_display_letter_mesh_layer_4_mat_override_b_1[];
extern Gfx rank_display_letter_mesh_layer_4_mat_override_c_2[];
extern Gfx rank_display_letter_mesh_layer_4_mat_override_d_3[];
extern Gfx rank_display_letter_mesh_layer_4_mat_override_f_4[];
extern Gfx rank_display_material_revert_render_settings[];
