extern const GeoLayout castle_rock_switch_opt1[];
extern const GeoLayout castle_rock_geo[];
extern Lights1 castle_rock_Rock_001_lights;
extern Lights1 castle_rock_Rock2_lights;
extern u8 castle_rock_ss_ceiling_2_i4_dark2_i8[];
extern u8 castle_rock_ss_ceiling_2_i4_light_i8[];
extern Vtx castle_rock_dl_mesh_layer_1_vtx_0[24];
extern Gfx castle_rock_dl_mesh_layer_1_tri_0[];
extern Gfx mat_castle_rock_Rock_001[];
extern Gfx mat_castle_rock_Rock2[];
extern Gfx castle_rock_dl_mesh_layer_1[];
extern Gfx castle_rock_dl_mesh_layer_1_mat_override_Rock2_0[];
extern Gfx castle_rock_material_revert_render_settings[];
